environment:
  EXE_BRANCH: "development"
  EXE_BRANCH_MACOS: "development"

  matrix:
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
     - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu2004
    #- APPVEYOR_BUILD_WORKER_IMAGE: macos
    #- APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave

for:
  - matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    install:
      - ps: >-
          $Env:LLVM_DIR="C:\Program Files\LLVM\bin"

          $PYVERSION = @("C:\\Python39","C:\\Python39-x64")

          foreach ($PY in $PYVERSION)
          {
              echo "====================================================================="
              echo "Python version $PY"
              echo "====================================================================="
              
              & "$PY\\python.exe" -m pip install --upgrade pip --no-warn-script-location
              & "$PY\\python.exe" -m pip install --upgrade setuptools --no-warn-script-location
              & "$PY\\python.exe" -m pip install wheel --no-warn-script-location
              & "$PY\\python.exe" -m pip install numpy --no-warn-script-location
              & "$PY\\python.exe" -m pip install -r requirements.txt --no-warn-script-location
              & "$PY\\python.exe" setup.py bdist_wheel
              & "$PY\\python.exe" -m pip install asammdf --no-index --find-links dist --no-deps --no-warn-script-location
              
              & "$PY\\python.exe" -m pip install -r test/requirements.txt --no-warn-script-location
              
          }

    build: off

    test_script:
      - ps: >-
          $PYVERSION = @("C:\\Python39","C:\\Python39-x64")

          foreach ($PY in $PYVERSION)
          {
              & "$PY\\Scripts\\pytest" test --color=yes --disable-pytest-warnings -vv -x
          }

    after_test:
      - ps: >-
          $PYVERSION = @("C:\\Python39","C:\\Python39-x64")

          foreach ($PY in $PYVERSION)
          {
              & "$PY\\python.exe" -Wignore setup.py bdist_wheel sdist
          }

    artifacts:
      - path: dist\*
      
  - matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    install:
      - ps: >-
          $Env:LLVM_DIR="C:\Program Files\LLVM\bin"

          $PYVERSION = @("C:\\Python36","C:\\Python36-x64","C:\\Python37","C:\\Python37-x64","C:\\Python38","C:\\Python38-x64")

          foreach ($PY in $PYVERSION)
          {
              echo "====================================================================="
              echo "Python version $PY $Env:APPVEYOR_REPO_BRANCH $Env:EXE_BRANCH"
              echo "====================================================================="
              
              & "$PY\\python.exe" -m pip install --upgrade pip --no-warn-script-location
              & "$PY\\python.exe" -m pip install --upgrade setuptools --no-warn-script-location
              & "$PY\\python.exe" -m pip install wheel --no-warn-script-location
              & "$PY\\python.exe" -m pip install numpy --no-warn-script-location
  
              & "$PY\\python.exe" -m pip install -r test/requirements.txt --no-warn-script-location
              
              if (($Env:APPVEYOR_REPO_BRANCH -eq $Env:EXE_BRANCH) -and ($PY -eq "C:\\Python37-x64")) {
                  & "$PY\\python.exe" -m pip install pywin32 lxml natsort psutil PyQt5>=5.13.1 pyqtgraph==0.12.1 PyQtWebEngine pyqtlet h5py fastparquet scipy hdf5storage snappy cChardet==2.1.5 chardet --no-warn-script-location
                  & "$PY\\python.exe" -m pip install -r requirements.txt --no-warn-script-location
                  & "$PY\\python.exe" setup.py bdist_wheel
                  & "$PY\\python.exe" -m pip install asammdf --no-index --find-links dist --no-deps --no-warn-script-location
                  & "$PY\\python.exe" -m pip install cmerg cryptography --no-warn-script-location
                  & "$PY\\python.exe" -m pip install pyinstaller --no-warn-script-location
                  & "$PY\\Scripts\\pyinstaller" asammdf.spec --clean -y --onefile --log-level WARN
                  & "$PY\\Scripts\\pyinstaller" asammdf.spec --clean -y --log-level WARN
                  
                  7z a -bso0 -bsp0 -mx9 dist\asammdfgui.zip dist\asammdfgui
                  
              } else {
                  & "$PY\\python.exe" -m pip install -r requirements.txt --no-warn-script-location
                  & "$PY\\python.exe" setup.py bdist_wheel
                  & "$PY\\python.exe" -m pip install asammdf --no-index --find-links dist --no-deps --no-warn-script-location
              }
          }

    build: off

    test_script:
      - ps: >-
          $PYVERSION = @("C:\\Python36","C:\\Python36-x64","C:\\Python37","C:\\Python37-x64","C:\\Python38","C:\\Python38-x64")

          foreach ($PY in $PYVERSION)
          {
              & "$PY\\Scripts\\pytest" test --color=yes --disable-pytest-warnings -vv -x
          }

    after_test:
      - ps: >-
          $PYVERSION = @("C:\\Python36","C:\\Python36-x64","C:\\Python37","C:\\Python37-x64","C:\\Python38","C:\\Python38-x64")

          foreach ($PY in $PYVERSION)
          {
              & "$PY\\python.exe" -Wignore setup.py bdist_wheel sdist
          }

    artifacts:
      - path: dist\*

  - matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: ubuntu2004

    build: off

    install:
      - sh: >-
          for PY in venv3.7 venv3.8 venv3.9
              do
                  echo "====================================================================="
                  echo "Python version $PY"
                  echo "====================================================================="
                  
                  source $HOME/$PY/bin/activate
                  
                  pip3 install --upgrade pip
                  pip3 install --upgrade setuptools
                  pip3 install wheel
                  pip3 install numpy
                  pip3 install -e .
                  pip3 install -r test/requirements.txt 
                  
                  if [[ $APPVEYOR_REPO_BRANCH == "development" && $PY == "venv3.7" ]]
                  then
                      pip3 install lxml natsort psutil PyQt5>=5.13.1 pyqtgraph==0.12.1 PyQtWebEngine h5py pyqtlet fastparquet scipy hdf5storage snappy cChardet==2.1.5 chardet --no-warn-script-location
                      pip3 install .
                      pip3 install cmerg cryptography
                      pip3 install pyinstaller
                      pyinstaller asammdf.spec --clean -y --onefile
                      cp dist\asammdfgui dist\asammfgui_onefile
                      pyinstaller asammdf.spec --clean -y
                  else
                      pip3 install .
                  fi
                  
                  deactivate
              done

    test_script:
      - sh: >-
          for PY in venv3.6 venv3.7 venv3.8 venv3.9
              do
                  source $HOME/$PY/bin/activate
                  pytest test --color=yes --disable-pytest-warnings -vv -x
                  deactivate
              done

    after_test:
      - sh: >-
          for PY in venv3.6 venv3.7 venv3.8 venv3.9
              do
                  source $HOME/$PY/bin/activate
                  python3 setup.py bdist_wheel
                  deactivate
              done

    artifacts:
      - path: dist\*

  - matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave

    build: off

    install:
      - sh: >-
          for PY in venv3.6 venv3.7 venv3.8 venv3.9
              do
                  echo "====================================================================="
                  echo "Python version $PY"
                  echo "====================================================================="
                  
                  source ~/$PY/bin/activate
                  
                  pip3 install --upgrade pip
                  pip3 install --upgrade setuptools
                  pip3 install wheel
                  pip3 install numpy
                  pip3 install .
                  pip3 install -r test/requirements.txt
                  
              done

    test_script:
      - sh: >-
          for PY in venv3.6 venv3.7 venv3.8 venv3.9
              do
                  source ~/$PY/bin/activate
                  pytest test --color=yes --disable-pytest-warnings -vv -x
                  deactivate
              done

    after_test:
      - sh: >-
          for PY in venv3.6 venv3.7 venv3.8 venv3.9
              do
                  source ~/$PY/bin/activate
                  python3 setup.py bdist_wheel
                  deactivate
              done

    artifacts:
      - path: dist\*
      
  - matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: macos

    build: off

    install:
      - sh: >-
          for PY in venv3.7 venv3.8 venv3.9
              do
                  echo "====================================================================="
                  echo "Python version $PY"
                  echo "====================================================================="
                  
                  source ~/$PY/bin/activate
                  
                  pip3 install --upgrade pip
                  pip3 install --upgrade setuptools
                  pip3 install wheel
                  pip3 install numpy
                  pip3 install -r test/requirements.txt
                  
                  if [[ $APPVEYOR_REPO_BRANCH == $EXE_BRANCH_MACOS && $PY == "venv3.7" ]]
                  then
                      pip3 install lxml natsort psutil PyQt5>=5.13.1 pyqtgraph==0.12.1 PyQtWebEngine h5py pyqtlet fastparquet scipy hdf5storage snappy cChardet==2.1.5 chardet --no-warn-script-location
                      pip3 install .
                      pip3 install cmerg cryptography
                      pip3 install pyinstaller
                      pyinstaller asammdf.spec --clean -y --onefile --log-level WARN
                      cp dist\asammdfgui dist\asammfgui_onefile
                      pyinstaller asammdf.spec --clean -y --log-level WARN
                  else
                      pip3 install .
                  fi
                  
                  deactivate
              done

    test_script:
      - sh: >-
          for PY in venv3.6 venv3.7 venv3.8 venv3.9
              do
                  source ~/$PY/bin/activate
                  pytest test --color=yes --disable-pytest-warnings -vv -x
                  deactivate
              done

    after_test:
      - sh: >-
          for PY in venv3.6 venv3.7 venv3.8 venv3.9
              do
                  source ~/$PY/bin/activate
                  python3 setup.py bdist_wheel
                  deactivate
              done

    artifacts:
      - path: dist\*
